import { useEffect, useState, type ReactNode } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';

import { Fonts, Radius, Shadows, Spacing, Typography } from '@/constants/theme';
import { formatMoney } from '@/lib/money';
import { getPaymentLabel, getPlanItemState, getPlanView } from '@/services/plan-service';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { useTheme } from '@/hooks/use-theme';

export default function PlanScreen() {
  const theme = useTheme();
  const { snapshot, plan, goals } = getPlanView();
  const [startDay, setStartDay] = useState(1);
  const [periodOpen, setPeriodOpen] = useState(false);
  const [aiOpen, setAiOpen] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [applied, setApplied] = useState<string[]>([]);

  useEffect(() => {
    if (!aiOpen) return;
    setAiLoading(true);
    const timer = setTimeout(() => setAiLoading(false), 120);
    return () => clearTimeout(timer);
  }, [aiOpen]);

  return <ThemedView style={styles.page}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><ThemedText type="code" themeColor="muted" style={styles.eyebrow}>BUDGET PLAN</ThemedText><ThemedText type="title" style={styles.title}>Rencana</ThemedText><Pressable accessibilityRole="button" accessibilityLabel="Ubah Budget period" onPress={() => setPeriodOpen(true)}><ThemedText type="small" themeColor="muted">{startDay}–{startDay === 1 ? 30 : 30} Sep⌄</ThemedText></Pressable></View><Pressable accessibilityRole="button" accessibilityLabel="AI Suggestion" onPress={() => setAiOpen(true)} style={[styles.aiButton, { borderColor: theme.line, backgroundColor: theme.mint }]}><ThemedText type="smallBold" themeColor="pine">✦ AI Suggestion</ThemedText></Pressable></View>
    <ThemedView style={[styles.hero, { backgroundColor: theme.pine2 }]}><ThemedText type="code" style={{ color: theme.heroMuted }}>SALDO TERSEDIA</ThemedText><ThemedText style={[styles.heroAmount, { color: theme.heroText }]}>{formatMoney(snapshot.availableBalance)}</ThemedText><View style={[styles.heroStats, { borderTopColor: theme.heroDivider }]}><View><ThemedText type="small" style={{ color: theme.heroMuted }}>Tersedia bebas</ThemedText><ThemedText type="smallBold" style={{ color: theme.heroText }}>{formatMoney(snapshot.freeBalance)}</ThemedText></View><View><ThemedText type="small" style={{ color: theme.heroMuted }}>Terikat goal</ThemedText><ThemedText type="smallBold" style={{ color: theme.heroText }}>{formatMoney(snapshot.goalBalance)}</ThemedText></View></View></ThemedView>
    <View style={[styles.spare, { borderColor: theme.line, backgroundColor: theme.card }]}><View><ThemedText type="code" themeColor="muted">SPARE BUDGET</ThemedText><ThemedText type="subtitle">{formatMoney(snapshot.spareBudget)}</ThemedText><ThemedText type="small" themeColor="muted">Pendapatan − fixed expense − goal</ThemedText></View><ThemedText style={[styles.spareGlyph, { color: theme.pine }]}>◌</ThemedText></View>
    <PlanSection title="Pendapatan" action="+ Tambah" theme={theme}>{plan.incomeItems.map((item) => <PlanItem key={item.id} name={item.name} target={item.targetAmount} state={getPlanItemState(item.id)} action="Catat" color={theme.income} theme={theme} />)}</PlanSection>
    <PlanSection title="Fixed expense" action="+ Tambah" theme={theme}>{plan.fixedExpenseItems.map((item) => <PlanItem key={item.id} name={item.name} target={item.targetAmount} state={getPlanItemState(item.id)} action="Bayar" color={theme.expense} theme={theme} />)}</PlanSection>
    <PlanSection title="Goal" action="+ Tambah" theme={theme}>{goals.map((goal) => { const saved = goal.walletId === 'wallet-dana-nikah' ? 1750000 : 2000000; const achieved = saved >= goal.targetAmount; return <View key={goal.id} style={[styles.goal, { borderBottomColor: theme.line }]}><View style={styles.itemHeader}><ThemedText type="smallBold">{goal.name}</ThemedText><ThemedText type="smallBold" style={{ color: achieved ? theme.income : theme.gold }}>{achieved ? 'Tercapai' : formatMoney(saved)}</ThemedText></View><Progress value={Math.min(saved / goal.targetAmount * 100, 100)} color={achieved ? theme.income : theme.gold} theme={theme} /><ThemedText type="small" themeColor="muted">Target {formatMoney(goal.targetAmount)} · {formatMoney(goal.monthlyContribution)}/bulan</ThemedText></View>; })}</PlanSection>
    <PlanSection title="Alokasi" action="+ Tambah" theme={theme}>{plan.allocationItems.map((item) => <PlanItem key={item.id} name={item.name} target={item.targetAmount} state={getPlanItemState(item.id)} action="" color={getPlanItemState(item.id)?.overBudget ? theme.expense : theme.pine} theme={theme} />)}</PlanSection>
  </ScrollView>
  <Modal transparent animationType="slide" visible={periodOpen} onRequestClose={() => setPeriodOpen(false)}><Pressable style={[styles.overlay, { backgroundColor: theme.overlay }]} onPress={() => setPeriodOpen(false)}><View style={[styles.sheet, { backgroundColor: theme.card }]}><ThemedText type="sectionHeading">Budget period</ThemedText><ThemedText type="small" themeColor="muted">Pilih tanggal mulai</ThemedText>{[1, 5, 25].map((day) => <Pressable key={day} accessibilityRole="button" accessibilityLabel={`Mulai tanggal ${day}`} onPress={() => { setStartDay(day); setPeriodOpen(false); }} style={styles.sheetOption}><ThemedText type="smallBold" themeColor={startDay === day ? 'pine' : 'ink'}>Tanggal {day}</ThemedText></Pressable>)}</View></Pressable></Modal>
  <Modal transparent animationType="slide" visible={aiOpen} onRequestClose={() => setAiOpen(false)}><Pressable style={[styles.overlay, { backgroundColor: theme.overlay }]} onPress={() => setAiOpen(false)}><View style={[styles.sheet, { backgroundColor: theme.card }]}><ThemedText type="sectionHeading">✦ Saran untuk Budget plan</ThemedText>{aiLoading ? <View style={styles.loading}><ThemedText style={[styles.loadingGlyph, { color: theme.pine }]}>✦</ThemedText><ThemedText type="smallBold">Membaca pola keuanganmu…</ThemedText><ThemedText type="small" themeColor="muted">Sebentar ya.</ThemedText></View> : ['Naikkan alokasi Makan menjadi Rp 1.500.000', 'Sisihkan Rp 300.000 untuk Dana Nikah'].map((suggestion) => <View key={suggestion} style={[styles.suggestion, { borderTopColor: theme.line }]}><ThemedText type="small" style={styles.suggestionText}>{suggestion}</ThemedText><Pressable accessibilityRole="button" accessibilityLabel={`Terapkan ${suggestion}`} onPress={() => setApplied((current) => current.includes(suggestion) ? current : [...current, suggestion])}><ThemedText type="smallBold" themeColor={applied.includes(suggestion) ? 'income' : 'pine'}>{applied.includes(suggestion) ? '✓ Diterapkan' : 'Terapkan'}</ThemedText></Pressable></View>)}<Pressable accessibilityRole="button" accessibilityLabel="Tutup saran" onPress={() => setAiOpen(false)} style={styles.closeSheet}><ThemedText type="smallBold" style={{ color: theme.heroText }}>Mengerti</ThemedText></Pressable></View></Pressable></Modal>
  </ThemedView>;
}

function PlanSection({ title, action, children, theme }: { title: string; action: string; children: ReactNode; theme: ReturnType<typeof useTheme> }) { return <View style={styles.section}><View style={styles.sectionTitle}><ThemedText type="sectionHeading">{title}</ThemedText><ThemedText type="smallBold" themeColor="pine">{action}</ThemedText></View><ThemedView style={[styles.card, { borderColor: theme.line, backgroundColor: theme.card }]}>{children}</ThemedView></View>; }
function PlanItem({ name, target, state, action, color, theme }: { name: string; target: number; state?: { realizedAmount: number; progressPercent: number; paymentStatus?: { kind: string; paidAmount?: number; targetAmount?: number }; overBudget: boolean }; action: string; color: string; theme: ReturnType<typeof useTheme> }) { const progress = state?.progressPercent ?? 0; return <View style={[styles.item, { borderBottomColor: theme.line }]}><View style={styles.itemHeader}><View><ThemedText type="smallBold">{name}</ThemedText><ThemedText type="small" themeColor="muted">{formatMoney(state?.realizedAmount ?? 0)} dari {formatMoney(target)}</ThemedText></View>{action && <ThemedText type="smallBold" style={{ color }}>{action} →</ThemedText>}</View><Progress value={progress} color={state?.overBudget ? theme.expense : color} theme={theme} />{state?.overBudget ? <ThemedText type="smallBold" style={{ color: theme.expense }}>Melebihi Budget</ThemedText> : state?.paymentStatus && <ThemedText type="small" style={{ color }}>{getPaymentLabel(state.paymentStatus.kind, state.paymentStatus.paidAmount, state.paymentStatus.targetAmount)}</ThemedText>}</View>; }
function Progress({ value, color, theme }: { value: number; color: string; theme: ReturnType<typeof useTheme> }) { return <View style={[styles.progress, { backgroundColor: theme.line }]}><View style={[styles.progressFill, { backgroundColor: color, width: `${Math.min(value, 100)}%` }]} /></View>; }

const styles = StyleSheet.create({ page: { flex: 1 }, content: { padding: 21, paddingBottom: 40, width: '100%' }, header: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 }, headerCopy: { flex: 1 }, eyebrow: { ...Typography.eyebrow }, title: { fontSize: 29, lineHeight: 32 }, aiButton: { borderRadius: Radius.pill, borderWidth: 1, marginTop: 14, paddingHorizontal: 12, paddingVertical: 10 }, hero: { borderRadius: Radius.hero, marginBottom: 17, padding: 21, ...Shadows.hero }, heroAmount: { fontFamily: Fonts.serifBold, fontSize: 30, lineHeight: 34, marginVertical: 12 }, heroStats: { borderTopWidth: 1, flexDirection: 'row', gap: 28, paddingTop: 13 }, spare: { alignItems: 'center', borderRadius: 22, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 17, padding: 18 }, spareGlyph: { fontSize: 42 }, section: { marginBottom: 18 }, sectionTitle: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 }, card: { borderRadius: 19, borderWidth: 1, paddingHorizontal: 13 }, item: { paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth }, itemHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, progress: { borderRadius: 9, height: 5, marginVertical: 10, overflow: 'hidden' }, progressFill: { borderRadius: 9, height: '100%' }, goal: { paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth }, overlay: { flex: 1, justifyContent: 'flex-end' }, sheet: { borderTopLeftRadius: 27, borderTopRightRadius: 27, gap: 8, padding: 21 }, sheetOption: { borderTopWidth: StyleSheet.hairlineWidth, paddingVertical: 15 }, loading: { alignItems: 'center', paddingVertical: 35 }, loadingGlyph: { fontSize: 28, marginBottom: 12 }, suggestion: { alignItems: 'center', borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: 10, paddingVertical: 15 }, suggestionText: { flex: 1 }, closeSheet: { alignItems: 'center', backgroundColor: '#235B50', borderRadius: 13, marginTop: 8, padding: 13 }, });
