import { useEffect, useState, type ReactNode } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';

import { Fonts, Radius, Shadows, Spacing, Typography } from '@/constants/theme';
import { formatMoney } from '@/lib/money';
import { getReportNetSavingLabel, getReportView } from '@/services/report-service';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { useTheme } from '@/hooks/use-theme';

export default function ReportScreen() {
  const theme = useTheme();
  const { snapshot, expenses } = getReportView();
  const [range, setRange] = useState('3 bulan');
  const [insightOpen, setInsightOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  useEffect(() => { if (!insightOpen) return; setLoading(true); const timer = setTimeout(() => setLoading(false), 120); return () => clearTimeout(timer); }, [insightOpen]);
  const maxExpense = expenses[0]?.amount ?? 1;

  return <ThemedView style={styles.page}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><ThemedText type="code" themeColor="muted" style={styles.eyebrow}>REPORT</ThemedText><ThemedText type="title">Keuanganmu</ThemedText><ThemedText type="small" themeColor="muted">1–30 Sep⌄</ThemedText></View><Pressable accessibilityRole="button" accessibilityLabel="Tanya insight" onPress={() => setInsightOpen(true)} style={[styles.insightButton, { backgroundColor: theme.mint, borderColor: theme.line }]}><ThemedText type="smallBold" themeColor="pine">✦ Tanya insight</ThemedText></Pressable></View>
    <View style={[styles.summary, { borderColor: theme.line, backgroundColor: theme.card }]}><Metric label="Pendapatan" value={snapshot.totalIncome} color={theme.income} /><Metric label="Pengeluaran" value={snapshot.totalExpense} color={theme.expense} /><Metric label={getReportNetSavingLabel(snapshot.netSaving)} value={snapshot.netSaving} color={snapshot.netSaving < 0 ? theme.expense : theme.pine} /></View>
    <ChartCard title="Pengeluaran per kategori" theme={theme}><View style={styles.donutRow}><View style={[styles.donut, { borderColor: theme.expense, backgroundColor: theme.mint }]}><ThemedText type="smallBold">{formatMoney(snapshot.totalExpense)}</ThemedText><ThemedText type="small" themeColor="muted">total keluar</ThemedText></View><View style={styles.legend}>{expenses.map((item, index) => <Pressable key={item.categoryId} accessibilityRole="button" accessibilityLabel={`Lihat kategori ${item.name}`} onPress={() => router.push({ pathname: '/history', params: { categoryId: item.categoryId, categoryName: item.name } } as never)} style={styles.legendRow}><View style={[styles.dot, { backgroundColor: [theme.expense, theme.gold, theme.pine][index % 3] }]} /><ThemedText type="small" style={styles.legendName}>{item.name}</ThemedText><ThemedText type="small" themeColor="muted">{formatMoney(item.amount)}</ThemedText></Pressable>)}</View></View></ChartCard>
    <ChartCard title="Net saving" theme={theme}><View style={styles.rangeRow}>{['3 bulan', '6 bulan', '12 bulan'].map((option) => <Pressable key={option} accessibilityRole="button" accessibilityLabel={`Rentang ${option}`} onPress={() => setRange(option)}><ThemedText type="smallBold" themeColor={range === option ? 'pine' : 'muted'}>{option}</ThemedText></Pressable>)}</View><View style={[styles.chart, { borderBottomColor: theme.line }]}>{[35, 55, 43, 71, 62, 83].map((height, index) => <View key={index} style={[styles.bar, { backgroundColor: theme.pine, height: `${height}%` }]} />)}</View><View style={styles.months}>{['Jul', 'Agu', 'Sep'].map((month) => <ThemedText key={month} type="small" themeColor="muted">{month}</ThemedText>)}</View></ChartCard>
  </ScrollView><Modal transparent animationType="slide" visible={insightOpen} onRequestClose={() => setInsightOpen(false)}><Pressable style={[styles.overlay, { backgroundColor: theme.overlay }]} onPress={() => setInsightOpen(false)}><View style={[styles.sheet, { backgroundColor: theme.card }]}>{loading ? <View style={styles.loading}><ThemedText style={[styles.loadingGlyph, { color: theme.pine }]}>✦</ThemedText><ThemedText type="smallBold">Menghubungkan titik-titik…</ThemedText><ThemedText type="small" themeColor="muted">Membaca pola keuanganmu.</ThemedText></View> : <><ThemedText type="sectionHeading">Insight bulan ini</ThemedText><ThemedText style={styles.insightText}>Pengeluaran terbesar ada di kategori Makan. Net saving masih positif, jadi kamu punya ruang untuk menjaga alokasi tetap nyaman.</ThemedText><View style={[styles.takeaway, { backgroundColor: theme.mint }]}><ThemedText type="smallBold" themeColor="pine">Langkah kecil</ThemedText><ThemedText type="small" themeColor="pine">Coba cek kembali transaksi Makan minggu ini.</ThemedText></View><Pressable accessibilityRole="button" accessibilityLabel="Mengerti" onPress={() => setInsightOpen(false)} style={[styles.closeInsight, { backgroundColor: theme.pine }]}><ThemedText type="smallBold" style={{ color: theme.heroText }}>Mengerti</ThemedText></Pressable></>}</View></Pressable></Modal></ThemedView>;
}

function Metric({ label, value, color }: { label: string; value: number; color: string }) { return <View style={styles.metric}><ThemedText type="small" themeColor="muted">{label}</ThemedText><ThemedText type="smallBold" style={{ color, fontFamily: Fonts.mono }}>{formatMoney(value)}</ThemedText></View>; }
function ChartCard({ title, children, theme }: { title: string; children: ReactNode; theme: ReturnType<typeof useTheme> }) { return <ThemedView style={[styles.card, { backgroundColor: theme.card, borderColor: theme.line }]}><ThemedText type="sectionHeading">{title}</ThemedText>{children}</ThemedView>; }

const styles = StyleSheet.create({ page: { flex: 1 }, content: { padding: 21, paddingBottom: 40 }, header: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 }, eyebrow: { ...Typography.eyebrow }, insightButton: { borderRadius: Radius.pill, borderWidth: 1, marginTop: 14, paddingHorizontal: 12, paddingVertical: 10 }, summary: { borderRadius: 19, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 17, padding: 14 }, metric: { gap: 5 }, card: { borderRadius: 22, borderWidth: 1, marginBottom: 14, padding: 17 }, donutRow: { flexDirection: 'row', gap: 17, marginTop: 18 }, donut: { alignItems: 'center', borderRadius: 70, borderWidth: 13, height: 135, justifyContent: 'center', width: 135 }, legend: { flex: 1, justifyContent: 'center' }, legendRow: { alignItems: 'center', flexDirection: 'row', gap: 7, paddingVertical: 7 }, dot: { borderRadius: 4, height: 8, width: 8 }, legendName: { flex: 1, fontSize: 11 }, rangeRow: { flexDirection: 'row', gap: 14, justifyContent: 'flex-end', marginTop: 10 }, chart: { alignItems: 'flex-end', borderBottomWidth: 1, flexDirection: 'row', gap: 10, height: 130, justifyContent: 'center', marginTop: 8, paddingHorizontal: 17 }, bar: { borderTopLeftRadius: 4, borderTopRightRadius: 4, width: 23 }, months: { flexDirection: 'row', justifyContent: 'space-around', paddingTop: 7 }, overlay: { flex: 1, justifyContent: 'flex-end' }, sheet: { borderTopLeftRadius: 27, borderTopRightRadius: 27, padding: 21 }, loading: { alignItems: 'center', paddingVertical: 45 }, loadingGlyph: { fontSize: 29, marginBottom: 12 }, insightText: { fontSize: 13, lineHeight: 21, marginTop: 17 }, takeaway: { borderRadius: 14, gap: 5, marginVertical: 17, padding: 13 }, closeInsight: { alignItems: 'center', borderRadius: 13, padding: 13 }, });
